version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app # Caminho na instância EC2 onde a aplicação será colocada
permissions:
  - object: /home/ubuntu/app
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/stop_previous_container.sh
      timeout: 300
      runas: ubuntu
