name: CI/CD

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t henrique-teste-ezops .
        docker tag henrique-teste-ezops henriquesamu/henrique-teste-ezops:1.0.0
        docker push henriquesamu/henrique-teste-ezops:1.0.0

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 15.228.185.251 # Substitua pelo endereço IP ou nome do servidor
        username: ubuntu # Substitua pelo seu nome de usuário SSH
        key: ${{ secrets.SSH_PRIVATE_KEY }} # Substitua pelo conteúdo da chave privada SSH
        script: |
          docker stop henrique-container || true
          docker rm henrique-container || true
          docker pull henriquesamu/henrique-teste-ezops:1.0.0
          docker run -d -p 80:3000 --name henrique-container henriquesamu/henrique-teste-ezops:1.0.0


