name: CI/CD

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t henrique-teste-ezops .
        docker tag henrique-teste-ezops henriquesamu/henrique-teste-ezops:1.0.0
        docker push henriquesamu/henrique-teste-ezops:1.0.0

    - name: Deploy
      run: |
        docker stop henrique-container || true
        docker rm henrique-container || true
        docker run -d -p 8080:3000 --name henrique-container henriquesamu/henrique-teste-ezops:1.0.0


